In [10]:
import numpy as np

x = np.random.randint(0, 10000, size=(10,3))

print(x)

[[8609 1004 9842]
 [8368 6021 3711]
 [9289  296  815]
 [4785 7085 1483]
 [8027 2389 6089]
 [6244 2134 8935]
 [5232 4721 4723]
 [8329 4074 3162]
 [4630 1502 4839]
 [9051  607 2938]]
